name: Validate and Lint Packer Config

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: 1.11.2

      - name: Initialize Packer plugins
        run: packer init packer/ubuntu/

      - name: Validate Packer configuration
        run: packer validate packer/ubuntu/

      - name: Lint Packer configuration
        run: packer fmt -check -diff ./packer
